// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Snf99f2NuaYaUFk8KwnDKEW2xqna-So',
    appId: '1:361319922953:web:717738c7ef0b3178c567d8',
    messagingSenderId: '361319922953',
    projectId: 'vize-030121086-fc116',
    authDomain: 'vize-030121086-fc116.firebaseapp.com',
    storageBucket: 'vize-030121086-fc116.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt-BwKEU3n3DC235xpbECylogyGfQYbhg',
    appId: '1:361319922953:android:ca7bc658295e5d30c567d8',
    messagingSenderId: '361319922953',
    projectId: 'vize-030121086-fc116',
    storageBucket: 'vize-030121086-fc116.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo8wVJcITZNQh-9t9t7S-F0F1YBiy7Isw',
    appId: '1:361319922953:ios:99f4365c66ff2c7ac567d8',
    messagingSenderId: '361319922953',
    projectId: 'vize-030121086-fc116',
    storageBucket: 'vize-030121086-fc116.appspot.com',
    iosClientId: '361319922953-sps8d8bdqsbl9qqgb1oqq01mamma87ci.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo8wVJcITZNQh-9t9t7S-F0F1YBiy7Isw',
    appId: '1:361319922953:ios:99f4365c66ff2c7ac567d8',
    messagingSenderId: '361319922953',
    projectId: 'vize-030121086-fc116',
    storageBucket: 'vize-030121086-fc116.appspot.com',
    iosClientId: '361319922953-sps8d8bdqsbl9qqgb1oqq01mamma87ci.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
